### ISSUE TITLE
Unsure how to pass errors through from filemaker script.

### ISSUE THREAD

**Issue by JamesSCV** [GoyaPtyLtd/RESTfm#1]
We are currently developing a system that requires us to pass back custom error codes depending on why the filemaker script exits. When called, the script either returns the newly created record, the old record that should have been updated, or a random record. This happens regardless of any errors set within the filemaker script. What is the expected method of telling RESTfm that an error occurred within the script and passing that through to the client system?

**Comment by gav-** [comment]
This is just the way that the FileMaker Server XML/PHP API works, so I am closing this issue as "notabug". For RESTfm product support and assistance, please visit Goya's RESTfm support page here:
http://restfm.com/help
