### ISSUE TITLE
Installing on Windows 2016...

### ISSUE THREAD

**Issue by keawewong** [GoyaPtyLtd/RESTfm#15]
**A friendly installation report**

I have a Windows 2016 server, FMS 15 running on aws.amazon. Following are what I had to do to make RESTfm work.

- Web server (IIS) needs to be **manually** installed.
- And then inside Web server > Application Development, install the features below 
(they are all necessary):
    |-->asp, asp.net 4.6, cgi, ISAPI extension and filter.
- Go to Server Manager > Add roles and features to find all of the above.
- This will make php working with my fms and Windows 10 config. Therefore, RESTfm will work. 
- Amazon aws won't work if you have less that EC2 medium tier.

It took me many hours of trying. Luckily, I stumbled across an old post in 2010 dealing with the same issue, not seeing php working on windows 8 server. That gave me the clue to figure this out. Without that guy's post, I would never have figured it out. Therefore I would like to do my part of the contribution.

I hope this will help you happily REST away. :-)

**Comment by nickorr** [comment]
Thanks for this, much appreciated.  I'll add a note to the docs to refer to this if people are looking for it.

Cheers,
Nick
