### ISSUE TITLE
RFMfixFM02 in beta

### ISSUE THREAD

**Issue by laynebay** [GoyaPtyLtd/RESTfm#16]
Hey,
Nick pointed me to the 5.0 beta to install with FMS16.  Most of it was working as expected, but we ran into a problem and was able to revert to 4.0.9 and it works.  

5.0 Beta bug was using this: **RFMfixFM02=1**

Full URL:
```
httppost://dev.atlmac.com/RESTfm/GypsumHR/layout/device/85.json?key=*****&RFMformat=simple&RFMdata=data
persistent_id%3D"256E339563849ACCD79C0D3159A02C0A"&RFMfixFM02=1&RFMmethod=PUT
```

Cheers
Michael

**Comment by gav-** [comment]
Thanks for the feedback on the new beta. Do you happen to have a copy of the error output ?

Cheers,

gav.
