### ISSUE TITLE
FMS 16

### ISSUE THREAD

**Issue by keawewong** [GoyaPtyLtd/RESTfm#17]
Quick question please: Will RESTfm work on FMS 16? I just looked at the Filemaker new REST trial. It is REALLY primitive!!! I am thinking of upgrading my server to FMS16. I rather pay annual RESTfm sponsorship than using Filemake REST trial. (I know RESTfm is free. But I think we as FMP developers need to support awesome 3rd party solutions.)

Hope to hear from you and thanks.

**Comment by nickorr** [comment]
keawewong,

Yes, RESTfm works on 16.  We've got a beta that updates the mac installer for 16, but the main details all work as the PHP API hasn't changed at all.  Also the new server setup is quite different for master/worker servers from 15 and earlier, but the basic ideas are all the same.

And yes, we agree, RESTfm is very flexible compared to the REST API, but I'm glad the REST API is there and I hope they improve it.  For now we intend to support RESTfm indefinitely.

Cheers,
Nick
