### ISSUE TITLE
Webserver Custom Port Numbers

### ISSUE THREAD

**Issue by jsrcomp** [GoyaPtyLtd/RESTfm#2]
Curious if you plan to support non-standard port numbers for web server?
Currently running on port 81 and 4431, RestFM diagnostics fail from what appears to be redirection to port 80 and/or 443

**Comment by gav-** [comment]
Yes, we are looking in to supporting alternate ports in the report.php diagnostics page (via RESTfm.ini.php variables).

RESTfm will run just fine using alternate ports right now, it's just that the report page is unable to determine the correct ports automatically, and so it shows errors.

**Comment by gav-** [comment]
Just a note that this feature is now supported in v4.0.1
