### ISSUE TITLE
FMS 18

### ISSUE THREAD

**Issue by JamesSCV** [GoyaPtyLtd/RESTfm#23]
Will FMS 18 be supported? Is it already supported? I'm having some issues updating this to use FMS 18.

**Comment by nickorr** [comment]
Yes, 18 is supported, we've got a dev build with support for the Data API you can grab here :

https://www.dropbox.com/s/msbg2hq8e5r8kgp/RESTfm-dev-20190715-6716f4a.zip?dl=0

Any feedback or testing would be appreciated.

Thanks,
Nick

**Comment by sfpx2** [comment]
This does not seem to work with a find request.
https://mysite/RESTfm/mydatabase/layout/userinfo.json?RFMkey=akey&RFMsF1=FieldToSearch&RFMsV1=ValueToSearch

Was working with restfm and fms server 17.
With this build and fms 18 it returns all the records.
Am I missing something ?

P.s.
Any way to make it work with php ? (I get deprecated errors)

**Comment by nickorr** [comment]
Following up on an old issue, the new 5.2.5 is compatible with 18 and 19.  It does not yet work with the Data API.

Cheers,
Nick
