### ISSUE TITLE
FileMaker Server 19?

### ISSUE THREAD

**Issue by jontravers-pacsol** [GoyaPtyLtd/RESTfm#24]
Greetings,
I wanted to check in on the availability and functionality of RESTfm running on FileMaker Server 19.

Looking for some guidance as this issue occurs on every fresh install of FMS 19.
It is probably something simple like the an extra include.
I am not a PHP expert and defer to the collective support knowledge here.

With or without extracting the 
> FM_API_for_PHP_Standalone.zip to
C:\Program Files\FileMaker\FileMaker Server\HTTPServer\conf\RESTfm\FileMaker

into the latest RESTfm (v5.2.3) folder does not overcome the issue below.

The PHP error from the localhost/RESTfm/report.php page when clicking the 
http://localhost/RESTfm/RESTfm.php?RFMcheckFMAPI is as follows.

> PHP Warning:  md5_file(C:\Program Files\FileMaker\FileMaker Server\Web Publishing\publishing-engine\php\FileMaker/Error/sv.php): failed to open stream: No such file or directory in C:\Program Files\FileMaker\FileMaker Server\HTTPServer\conf\RESTfm\lib\RESTfm\diagnostic_checks.php on line 59

I would note that the mentioned sv.php does not look exist at the paths mentioned in the error.

Here is the log:
OK: RESTfm version
  5.2.3/20190606-181adf3
OK: PHP version
  7.1.19
  C:\Program Files\FileMaker\FileMaker Server\Web Publishing\publishing-engine\php\php.ini
OK: PHP PDO drivers
  none
OK: Web Server version
  Microsoft-IIS/10.0
OK: Host Server version
  Operating System Name : Windows NT
  Host Name             : 2CC59C
  Release Name          : 10.0
  Version Information   : build 14393 (Windows Server 2016)
  Machine Type          : AMD64
OK: Host Server date
  2020-10-29 11:53:12 -06:00 (MDT - America/Denver)
OK: Install location
  C:\Program Files\FileMaker\FileMaker Server\HTTPServer\conf\RESTfm
OK: baseURI (RESTfm.ini.php)
  /RESTfm
OK: Web server redirect to RESTfm.php
  <a href="http://localhost/RESTfm/?RFMversion">http://localhost/RESTfm/?RFMversion</a>
  OK
ERROR: FileMaker PHP API
  <a href="http://localhost/RESTfm/RESTfm.php?RFMcheckFMAPI">http://localhost/RESTfm/RESTfm.php?RFMcheckFMAPI</a>
  FileMaker PHP API not found in PHP include path.
ERROR: FileMaker Server connection test
  Cannot test, FileMaker PHP API not found.
WARN: SSL enforced (RESTfm.ini.php)
  SSLOnly not TRUE in RESTfm.ini.php
  SSL is highly recommended to protect data, usernames and passwords from eavesdropping.
OK: PHP XSL extension
  OK

Thank you,
Jonathan Travers
jon.travers@pacific-solutions.com
https://www.pacific-solutions.com/

**Comment by nickorr** [comment]
Jonathan,

Yes, the PHP API doesn't change much any more, so it's really just our OS and server checking code that looks at newer OS releases.  

This version has all the bits up dated for newer OS versions, and we'll have an official release soon too I hope.

Cheers,
Nick

[RESTfm-dev-20200507.zip](https://github.com/GoyaPtyLtd/RESTfm/files/5461621/RESTfm-dev-20200507.zip)

**Comment by jontravers-pacsol** [comment]
Hi Nick,
Thank you for the dev RESTfm download.
This has helped get beyond the issue.
We look forward to the official release.

Much appreciated,
Jonathan Travers
jon.travers@pacific-solutions.com
https://www.pacific-solutions.com/

> Jonathan,
> 
> Yes, the PHP API doesn't change much any more, so it's really just our OS and server checking code that looks at newer OS releases.
> 
> This version has all the bits up dated for newer OS versions, and we'll have an official release soon too I hope.
> 
> Cheers,
> Nick
> 
> [RESTfm-dev-20200507.zip](https://github.com/GoyaPtyLtd/RESTfm/files/5461621/RESTfm-dev-20200507.zip)

**Comment by emaccormick** [comment]
Hi Nick,
We've done a new FMS19 install with the more recent RESTfm release (5.2.4) and had the exact same issue Jonathan had using 5.2.3.  
We've switched to  RESTfm-dev-20200507 successfully, but our IT people would prefer a release version.  

Ethan MacCormick
Performance Systems Development

**Comment by nickorr** [comment]
All,

I've done a 5.2.5 which correctly picks up the new API and should work now.  Let me know if you see any issues.

Cheers,
Nick
