### ISSUE TITLE
Class Section needs to implement Countable. PHP >=7.2 breaks FormatHTML

### ISSUE THREAD

**Issue by JamesSCV** [GoyaPtyLtd/RESTfm#26]
With php 7.2, any argument to count must be "Countable".
`lib/RESTfm/Format/FormatHtml.php` calls count on line 88 using the `$section` variable created on line 84. `$section` is a Section object defined in `lib/RESTfm/Message/Section.php` which is not implementing Countable resulting in a warning being thrown.

Adding the following to lib/RESTfm/Message/Section.php should implement Countable and fix the warning.

insert at line 22 `use Countable;`
Change class declaration to `class Section implements SectionInterface, Countable {...}`
Add count method to the class similar to the following:
```
/**
 * Returns an integer count of the number of rows.
 */
public function count() {
  if ($this->getDimensions() == 1 && count($this->getRows()) > 0) {
    return 1;
  }
  if ($this->getDimensions() > 1) {
    return count($this->getRows());
  }
  return 0;
}
```

**Comment by nickorr** [comment]
James, Thanks for this.  Any chance you can submit a change request here with these changes?

**Comment by gav-** [comment]
What version of RESTfm are you using JamesSCV?

**Comment by JamesSCV** [comment]
I created a PR against this issue. See PR #27

**Comment by JamesSCV** [comment]
@gav- I'm using version 5.2.6 and PHP 7.4, but the PHP change that caused this issue is from PHP 7.2 https://www.php.net/manual/en/migration72.incompatible.php#migration72.incompatible.warn-on-non-countable-types
