### ISSUE TITLE
Web server redirect to RESTfm.php, Redirection not working

### ISSUE THREAD

**Issue by amanbolat** [GoyaPtyLtd/RESTfm#3]
Tried many times install on ubuntu 14, and always this error.
Checked all apache configs, and yet show this error.

http://107.170.1.19/RESTfm/?RFMversion
Redirection not working, index.html was returned instead.
Check the Apache httpd configuration has 'AllowOverride All' for the RESTfm directory.

OK: RESTfm version
  4.0.1/UNKNOWN
OK: PHP version
  5.5.9-1ubuntu4.14
OK: PHP PDO drivers
  mysql
OK: Web Server version
  Apache/2.4.7 (Ubuntu)
OK: Host Server version
  Operating System Name : Linux
  Host Name             : crossasia-ru-erp-NY2
  Release Name          : 3.13.0-83-generic
  Version Information   : #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016
  Machine Type          : x86_64
OK: Host Server date
  2016-04-20 06:33:14 -04:00 (EDT - America/New_York)
OK: Install location
  /var/www/html/RESTfm
OK: baseURI (RESTfm.ini.php)
  /RESTfm
ERROR: Web server redirect to RESTfm.php
  <a href="http://107.170.1.19/RESTfm/?RFMversion">http://107.170.1.19/RESTfm/?RFMversion</a>
  Redirection not working, index.html was returned instead.
  Check the Apache httpd configuration has 'AllowOverride All' for the RESTfm directory.
OK: FileMaker PHP API
  <a href="http://107.170.1.19/RESTfm/RESTfm.php?RFMcheckFMAPI">http://107.170.1.19/RESTfm/RESTfm.php?RFMcheckFMAPI</a>
  Found at path : /var/www/html/RESTfm/FileMaker/FileMaker.php
  Version       : 13
ERROR: FileMaker Server connection test
  http://127.0.0.1
  FileMaker Web Publishing Engine not found at configured hostspec.
WARN: SSL enforced (RESTfm.ini.php)
  SSLOnly not TRUE in RESTfm.ini.php
  SSL is highly recommended to protect data, usernames and passwords from eavesdropping.
ERROR: PHP XSL extension
  Not Loaded. XSLT will not function.
  Only RESTfm .simple, .xml, .json and .html formats are available.

  Check that your Operating System has PHP XSL/XML packages installed.

**Comment by gav-** [comment]
Hi Amanbolat,

There is an unfortunate bug in the version of Apache the ships with
Ubuntu 14.04 which interferes with the redirect.

If you are positive you have enabled everything, then try editing
.htaccess and remove the comment(#) from the line:
DirectoryIndex disabled

(This isn't the default setting because it interferes with the other
setup diagnostics).

Regards,

Gavin.

**Comment by amanbolat** [comment]
Thank you for quick reply. Can u say, what version of linux and apache you already tested, and can be used for production?

**Comment by gav-** [comment]
http://www.restfm.com/restfm-manual/install/advanced-installations
"A minimum of PHP 5.2.11 with Apache 2 web server are required."

There's nothing wrong with using Apache 2.4.7 as shipped with Ubuntu 14.04, it's just an issue during the initial setup.

**Comment by amanbolat** [comment]
gav-, Thank you very much. 
Now it works!
