### ISSUE TITLE
Web server redirect to RESTfm.php not working.

### ISSUE THREAD

**Issue by Luidog** [GoyaPtyLtd/RESTfm#4]
It seems that I can't get web server redirect to work and I can't find documentation on what it needs.

Here is the report:

```
OK: RESTfm version
  4.0.2/20160421-05839cf
OK: PHP version
  5.5.14
OK: PHP PDO drivers
  mysql, sqlite
OK: Web Server version
  Apache/2.4.16 (Unix) OpenSSL/0.9.8zg
OK: Host Server version
  Operating System Name : Darwin
  Host Name             : Concierge-Cleaning-Services.local
  Release Name          : 14.5.0
  Version Information   : Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64
  Machine Type          : x86_64
OK: Host Server date
  2016-05-01 22:04:01 -07:00 (PDT - America/Los_Angeles)
OK: Install location
  /Library/FileMaker Server/HTTPServer/htdocs/RESTfm
OK: baseURI (RESTfm.ini.php)
  /RESTfm
ERROR: Web server redirect to RESTfm.php
  <a href="http://localhost/RESTfm/?RFMversion">http://localhost/RESTfm/?RFMversion</a>

  * Redirection not working, index.html was returned instead.

  Instructions:


  FileMaker Server 13/14 on Apple OSX instructions:

   - Execute the RESTfm installer script by typing the following in a terminal:
      sudo bash "/Library/FileMaker Server/HTTPServer/htdocs/RESTfm/contrib/install-RESTfm.OSX/install-RESTfm.OSX.command"

  - Reload this page.
OK: FileMaker PHP API
  <a href="http://localhost/RESTfm/RESTfm.php?RFMcheckFMAPI">http://localhost/RESTfm/RESTfm.php?RFMcheckFMAPI</a>
  Found at path : /Library/FileMaker Server/Web Publishing/publishing-engine/php/yosemite/lib/php/FileMaker.php
  Version       : 14
WARN: FileMaker Server connection test
  http://127.0.0.1
  <?xml version ="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE fmresultset PUBLIC "-//FMI//DTD fmresultset//EN" "http://127.0.0.1:16021/fmi/xml/fmresultset.dtd"><fmresultset xmlns="http://www.filemaker.com/xml/fmresultset" version="1.0"><error code="4"></error><product build="04/24/2015" name="FileMaker Web Publishing Engine" version="14.0.1.147"></product><datasource database="" date-format="" layout="" table="" time-format="" timestamp-format="" total-count="0"></datasource><metadata></metadata><resultset count="0" fetch-size="0"></resultset></fmresultset>Connection is OK, but a warning applies:
  FileMaker Server allowed the Guest Account to list databases.
  The FileMaker Server Admin Console should be used to set Database Server -> Security to: 
    'List only the databases each user is authorized to access'
WARN: SSL enforced (RESTfm.ini.php)
  SSLOnly not TRUE in RESTfm.ini.php
  SSL is highly recommended to protect data, usernames and passwords from eavesdropping.
OK: PHP XSL extension
  OK
```

I manually added 

```
# RESTfm - Mac OS X Apache 2.4 httpd config file for:
#          FileMaker Server <= 12 and standalone systems without FMS installed.
<Directory "/Library/WebServer/Documents/RESTfm">
    Options +SymLinksIfOwnerMatch
    AllowOverride All
    Require all granted
</Directory>
```

to my http.conf and restarted apache. No dice

**Comment by gav-** [comment]
The report you have shown includes instructions. Did you follow this part? : 

```
FileMaker Server 13/14 on Apple OSX instructions:

   - Execute the RESTfm installer script by typing the following in a terminal:
      sudo bash "/Library/FileMaker Server/HTTPServer/htdocs/RESTfm/contrib/install-RESTfm.OSX/install-RESTfm.OSX.command"
```

We no longer recommend editing httpd.conf manually on OS X as the FileMaker start-up script for Apache may overwrite it (depending on how you edit it).

**Comment by Luidog** [comment]
@gav- I did rerun the installer. I am going to reinstall FM Server and see if it will reset the web publishing engine. I was hoping you could fill me in how what RestFM is trying to redirect from to. Also Is this the best place to post this issue. I can't confirm that it is an environmental issue. I posted here since I saw a recently closed issue where the environment was Ubuntu. Thank you!

**Comment by Luidog** [comment]
@gav - I found the issue. It was my FM Server install and apache. I think I will dive deeper into this to see where I went wrong.

**Comment by gav-** [comment]
>  I was hoping you could fill me in how what RestFM is trying to redirect from to. 

The .htaccess file gives the Apache rewrite rules that are used to redirect all URIs to RESTfm.php. Correct function of the .htaccess file requires appropriate permissions to be configured in httpd.conf.

The OS-X install script selects the approriate httpd-RESTfm.*.conf from the contrib directory and modifies the FMS-Apache httpd.conf (in a manner compatible with FMS) to include said file (and also handles restarting the FMS-Apache service).

It's certainly not clear why your system did not work in this instance (re-installing FMS appears to be a common panacea).

> Also Is this the best place to post this issue. I can't confirm that it is an environmental issue. I posted here since I saw a recently closed issue where the environment was Ubuntu. Thank you!

Right, this github issue tracking is for software bugs, not for product support. Product support is provided through a sponsorship program: http://restfm.com/help

I do realise it might not always be clear if you have found a bug or not.

**Comment by Luidog** [comment]
@gav- thanks. In the future I will head to the support section you reference. Have you thought at all about opening up the documentation here for things like this? If I had a bit more documentation to go on, I would have referenced that rather than post a bug report. I would be willing to pitch in.
