### ISSUE TITLE
Better Authentication Documentation

### ISSUE THREAD

**Issue by Luidog** [GoyaPtyLtd/RESTfm#5]
I can't seem to Authenticate any server calls using Angular 2.  I have read the documentation here:

http://www.restfm.com/restfm-manual/web-api-reference-documentation/authentication

But I cat seem to get the basic authentication method or the RFMkey=<key> method to work. 

I have tried calling username:password@server/restfm/database and also tried modifying the RESTfm.ini.php configuration file.

 I know modifying this file works because I can change the 401 vs 403 setting and watch the change on the front end. Can anyone point me toward good documentation or give me a simple authentication example. 

I have no problem writing up the documentation for others once I can figure it out. 

What is restfm Auth looking for?

**Comment by Luidog** [comment]
I am currently looking into setting the Authorization Basic in the header at the moment. The link in the documentation lead me to believe that this example:

https://Aladdin:OpenSesame@www.example.com/index.html

Was what it was looking for. Seems like I overlooked the Authorization Basic Header setting

**Comment by Luidog** [comment]
I apologize for opening two simple documentation issues and closing them same day. Authentication does require a header be set rather than URL inline password.

**Comment by gav-** [comment]
> I can't seem to Authenticate any server calls using Angular 2. I have read the documentation here:
> 
> http://www.restfm.com/restfm-manual/web-api-reference-documentation/authentication

I'm not sure how this part could be clearer, the link clearly states that RESTfm supports basic access authentication (where basic access authentication is a HTTP standard).

> The link in the documentation lead me to believe that this example:
> 
> https://Aladdin:OpenSesame@www.example.com/index.html

Putting a username:password@ at the beginning of the URI is purely a HTTP client feature, and not a part of HTTP itself. The client application (if supported) will set the "Authorization: Basic" HTTP request header, stripping the username and password out of the URI before submitting the request to the server.

I would suggest using a browser for testing/development with RESTfm as it is trivial to perform most operations from the URL bar. (You might consider something like the firebug plugin that lets you inspect network traffic, including headers).  Then translate your discoveries into your client application.

> Can anyone point me toward good documentation . . .
> 
> I have no problem writing up the documentation for others once I can figure it out. 

I look forward to your contribution.

**Comment by Luidog** [comment]
> I'm not sure how this part could be clearer, the link clearly states that RESTfm supports basic access 
>  authentication (where basic access authentication is a HTTP standard).

It could be clearer by stating that the authentication is set in a header, "Authorization Basic: ". Although I agree and you are right this is an HTTP standard. However it is one standard among many. Alternatively stating that that it is referencing the Authorization Basic **Scheme**. Then It can not be confused at all.

 I did figure it out shortly after posting here but perhaps providing a link to the actual authorization docs would help:

[https://tools.ietf.org/html/rfc1945#section-11.1](url)

Or adding the Wikipedia example directly to the docs will make it clearer:

> When the user agent wants to send the server authentication credentials it may use the Authorization >field.
> 
> The Authorization field is constructed as follows:
> 
> The username and password are combined into a string separated by a colon, e.g.: username:password
> The resulting string is encoded using the RFC2045-MIME variant of Base64, except not limited to 76 char/line.
> The authorization method and a space i.e. "Basic " is then put before the encoded string.
> For example, if the user agent uses Aladdin as the username and OpenSesame as the password then >the field is formed as follows:
> 
> Authorization: Basic QWxhZGRpbjpPcGVuU2VzYW1l

It would be trivial to add this to your docs. You also have the added benefit of not requiring a user to follow a link and dig through Wikipedia which can change at any time.

> I would suggest using a browser for testing/development with RESTfm as it is trivial to perform most operations from the URL bar. (You might consider something like the firebug plugin that lets you inspect network traffic, including headers). Then translate your discoveries into your client application.

I used postman. I hope this helps others. 

I am not trying to nitpick your work. I genuinely am trying to be helpful here. If You would prefer I not just let me know.
