### ISSUE TITLE
Portals and Related Sets

### ISSUE THREAD

**Issue by amanbolat** [GoyaPtyLtd/RESTfm#6]
What about portals and related records? When RESTfm will support  it?

**Comment by nickorr** [comment]
Amanbolat,

We have no plans to support portals in RESTfm.  It doesn't really work well with a REST model unless you also have transactions, which the PHP API doesn't support.

You can still do multiple related data sets via different layouts, but they need to be done in different requests.  Alternatively you can script changes to related records.

Cheers,
Nick
